data:
  raw_data_path: "data/raw/creditcard2023.csv"
  x_test_path: "data/data_test/X_test.csv"
  y_test_path: "data/data_test/Y_test.csv"
  x_train_path: "data/data_train/X_train.csv"
  y_train_path: "data/data_train/Y_train.csv"
split:
  test_size: 0.2
  random_state: 42
  stratify: true
  target_column: "Class"
sampling:
  n_samples: 200
  ratio: 0.30
model:
  model_path: "models/randomForestModel.joblib"